### ISSUE TITLE
Setup MSK Cluster for Tests

### ISSUE THREAD

**Issue by mgolchert-inwt** [INWTlab/r-kafka#10]
We use this issue for documentation purposes because we need to setup an MSK cluster for testing.

**Comment by mgolchert-inwt** [comment]
We setup an MSK cluster on AWS with the following configuration:

- custom create
- provisioned cluster
- Kafka version: 2.8.1
- 3 brokers of type kafka.t3.small (1 broker per zone)
- 10 GB storage per broker
- private subnets
- 2 security groups: default and Oben72 
- unauthenticated access

After the cluster has been set up we were able to connect to it using the following python code:

```
from confluent_kafka import Consumer, Producer


bootstrap_servers = "bootstrap_servers"  # replace with bootstrap servers

conf = {
    "bootstrap.servers": bootstrap_servers,
    "security.protocol": "ssl",
    "group.id': "kafka-r-client-performance-test"
}

consumer = Consumer(conf)
producer = Producer(conf)
consumer.subscribe(["hackathon-test-topic"])

while True:
    msg = consumer.poll(timeout=1.0)
    if msg is None:
        print("continue")
        continue
    record_value = msg.value()
    print(record_value)

producer.produce("hackathon-test-topic", key="test-michelle", value="xxx")
producer.flush()

```

Before being able to read and write from/to the cluster a topic has to be created using the following code:

```
from confluent_kafka.admin import AdminClient, NewTopic

admin_client = AdminClient({
    "bootstrap.servers": bootstrap_servers,
    "security.protocol'" "ssl",
})

topic_list = [NewTopic("hackathon-test-topic", 10, 3)]
admin_client.create_topics(topic_list)

# check if it worked
producer.list_topics()
topic_metadata = producer.list_topics()
topic_metadata.topics.get("hackathon-test-topic")
```

**Comment by aneudecker** [comment]
Setup EC2 instance for testing:

- Ubuntu 22.04
- t2.medium (2 CPU / 4GB Memory)
- 20GB  Storage

**Comment by mgolchert-inwt** [comment]
@aneudecker I think we can close this issue right?

**Comment by aneudecker** [comment]
Correct
