### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by wahani** [INWTlab/r-kafka#12]
Can we change the name of the package from kafkaClient to 

- kafka
- rkafka (pkg on CRAN is archived, don't know if we can just recycle it)
- ...

Reason: We may add admin features and general utilities later on (they are supported by libkafka anyways) as well as general tooling. So I would like to have a short, generic, and all lower name.

**Comment by aneudecker** [comment]
We decided to go with `kafka` as this name is available and we are planning to provide a generic package to interact with a kafka cluster at some point
