### ISSUE TITLE
Support other operating systems

### ISSUE THREAD

**Issue by aneudecker** [INWTlab/r-kafka#2]
The R package should be functional on all common operating systems (main linux distributions, macOS, Windows).

Hints:
- Create Makevars file dynamically to allow for different compiler arguments
- Check for other Rcpp package for examples: https://github.com/RcppCore/RcppArmadillo/, https://github.com/eddelbuettel/rcppgsl/
- Use GNU Autoconf to create configure file https://www.gnu.org/software/autoconf/

**Comment by wahani** [comment]
We currently have

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-commit.R:21:3'): Committing throws no error ────────────────────
<Rcpp::exception/C++Error/error/condition>
Error: Error: Failed commit: Local: No offset stored
Backtrace:
    ▆
 1. └─consumer$commit(async = FALSE) at test-commit.R:21:3

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 8 ]
Error: Error: Test failures
Execution halted
```

in https://github.com/INWTlab/r-kafka-client/actions/runs/7033691872/job/19140093058?pr=9

On MacOS.

**Comment by aneudecker** [comment]
It was possible to compile the cpp into .o files using the following Makevars.win and putting the header files (rdkafkacpp.h) into `inst/include/librdkafka`:

```
PKG_CXXFLAGS = -I../inst/include
```

However the last step threw a lot of errors like
```
   [...]/consumer.cpp:16: undefined reference to `__imp__ZN7RdKafka13KafkaConsumer6createEPKNS_4ConfERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
```

This makes sense as the library was not included yet. But all attempts to link to the library were not successful, i.e. putting the `
*.lib` files into the lib folder and running
```
PKG_LIBS = -L../lib -llibrdkafkacpp
```

**Comment by aneudecker** [comment]
It's now possible to run the package on windows, potentially with some manual steps involved. As we need to change the process anyway when publishing to CRAN this should be okay for now.

**Comment by aneudecker** [comment]
We can now support all main operating systems (windows, macos, linux). Pipeline tests however are currently running under linux
